---
name: "Educación e Interculturalidad: Aproximación Crítica y Decolonial en Contexto Indígena"
title: "Educación e Interculturalidad: Aproximación Crítica y Decolonial en Contexto Indígena"
autores: ["Segundo Quintriqueo", "Daniel Quilaqueo"]
libro: "Educación e Interculturalidad: Aproximación Crítica y Decolonial en Contexto Indígena"
tipo: "Libro"
categories: 2019
keywords: ["2019", "Libro", "Educación Intercultural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2019_KARIAS/educacion-e-interculturalidad_Cap_libros.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo.qmd), {{< meta autores.2 >}}    
**Libro**: {{< meta libro >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}   
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: Este libro aporta una aproximación crítica y decolonial de la investigación en 
educación en contextos indígenas e interculturales. Surge de la necesidad por 
promover espacios de reflexión, discusión y análisis en vinculación recíproca con investigadores a nivel internacional, nacional y local que trabajan la línea de educación e interculturalidad. Asimismo, plantea el desafío de divulgar al contexto escolar los resultados de investigaciones empíricas y reflexiones teóricas, para aportar a una mejor comprensión y explicación de los problemas de la educación intercultural en ‘contextos de colonización’. Presenta diecinueve artículos que fueron presentados como ponencias en el IV Congreso Internacional sobre Educación e Interculturalidad, realizado el año 2017 por la Red Interuniversitaria sobre Educación e Interculturalidad (RIEDI). En este evento, se planteó la necesidad de producir nuevos conocimientos científicos y metodológicos, en perspectiva crítica, sobre educación intercultural, para favorecer el desarrollo social y el buen vivir de los pueblos. Al mismo tiempo, se propuso generar espacios de reflexión y co-construcción de conocimientos con otras instituciones y actores sociales involucrados en el desarrollo de la educación y la interculturalidad. El eje principal de las discusiones, fue la pluralidad epistemológica, como desafío para avanzar hacia un método co-constructivo en la producción de nuevos conocimientos científicos en educación para contexto indígena y no indígena.   


**BibTeX**:
```bibtex
@book{quintriqueo2019educacion,
  author = {Quintriqueo, Segundo and Quilaqueo, Daniel},
  title = {{< meta title >}},
  publisher = {Editorial},
  year = {{< meta categories.1 >}},
  address = {Ciudad o país},
  edition = {edición},
  isbn = {ISBN}
}
```
