---
name: "Contenidos Educativos Mapuches y Espacios Ecológicos-Culturales en La Araucanía: Desafíos para una Educación Intercultural"
title: "Contenidos Educativos Mapuches y Espacios Ecológicos-Culturales en La Araucanía: Desafíos para una Educación Intercultural" 
autores: ["Elias Andrade", "Segundo Quintriqueo", "Katerin Arias", "Fernando Peña"]
venue: "Diálogo Andino"
tipo: "Revista"
categories: 2022
keywords: ["2022", "Diálogo Andino", "Contenidos Educativos", "Conocimiento Indígena", "Construcción de Saberes", "Conocimiento Educativo Familiar", "Espacios Ecológicos-Culturales"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/ART_8_Arias-Ortega_Dialogo Andino_scopus_2022.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Segundo Quintriqueo.qmd), [{{< meta autores.3 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.4 >}}
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El artículo explora el conocimiento indígena, que en términos contextuales está relacionado con espacios ecológicos-culturales (EE-C), donde se articula la sociedad, el medioambiente y la espiritualidad que otorgan un sentido del lugar, asociado a una identidad y pertenencia sociocultural. El objetivo de este trabajo es reflexionar acerca de la importancia de incorporar los saberes y conocimientos educativos mapuches asociados a los espacios ecológicos-culturales, para contribuir con una base de conocimientos que permitan contextualizar la educación escolar, desde un enfoque educativo intercultural. La metodología consistió en una revisión sistemática de la literatura normativa y científica a nivel nacional e internacional para comprender y explicar el problema. Se concluye que: 1) los contenidos educativos mapuches, tienen directa relación con la mantención de los EE-C; 2) existe desconocimiento de los profesores respecto de contenidos educativos asociados a EE-C, quedando el currículum escolar circunscrito a una mirada eurocéntrica-occidental y 3) se requiere que el currículo nacional progresivamente descentralice la educación intercultural, de tal manera, que toda la población en edad escolar desarrolle competencias interculturales en relación a los EE-C.


**BibTeX**:
```bibtex
@article{andrade2022contenidos,
  author = {Andrade, Elias and Quintriqueo, Segundo and Arias, Katerin and Peña Fernando},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {67},
  number = {},
  pages = {88-98},
  doi = {}
}
```
