---
name: "Desafíos de la Educación desde una Interculturalidad Crítica y Decolonial en Contextos Indígenas"
title: "Desafíos de la Educación desde una Interculturalidad Crítica y Decolonial en Contextos Indígenas"
autores: ["Segundo Quintriqueo Millán", "Katerin Arias-Ortega"]
libro: "Decolonialidad e Interculturalidad Crítica"
capitulo: "7"
tipo: "Capítulo de Libro"
categories: 2024
keywords: ["2024", "Capítulo de Libro"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/CAP_libro1_Arias-Ortega_2024_Referato.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo Millán.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd)    
**Libro**: {{< meta libro >}}   
**Capítulo**: {{< meta capitulo >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El capítulo de libro discute los desafíos epistemológicos de una educación intercultural crítica decolonial en contextos indígenas, que permita avanzar en la transformación sociocultural hegemónica característica de los sistemas educativos escolares, para transitar a una formación de personas indígenas y no indígenas, desde una educación intercultural como proyecto social, ético, político y epistemológico. Sostenemos que, una educación intercultural como proyecto social, requiere de procesos de enseñanza y aprendizaje que reconozcan la diversidad social y cultural, para construir una forma de ver y comprender el mundo en diferentes perspectivas.

Una educación como proyecto ético, busca promover comunidades escolares seguras, integradoras, colaboradoras y estimulantes, para el aprendizaje de los estudiantes de distintas comunidades, en perspectiva local y global, a partir de los principios de la pedagogía y educación indígena asociados a la inteligencia experimental y emocional. Una educación como proyecto político, busca asegurar la materialización de un enfoque educativo intercultural como un foco central del proceso de mejora e innovación, desde políticas educativas que propicien y refuercen la participación de los actores del medio.


**BibTeX**:
```bibtex
@incollection{quintriqueo2024desafios,
  author = {Quintriqueo, Segundo and Arias, Katerin},
  title = {{< meta title >}},
  booktitle = {{< meta libro >}},
  editor = {},
  publisher = {Ariadna Ediciones},
  year = {{< meta categories.1 >}},
  chapter = {{< meta capitulo >}},
  pages = {130-},
  address = {Santiago de Chile}
}
```
