---
name: "Desafíos de la relación familia-escuela en contexto mapuche: aproximación desde los profesores"
title: "Desafíos de la relación familia-escuela en contexto mapuche: aproximación desde los profesores"
autores: ["Katerin Arias", "Mariela Gajardo", "Juan Sierpe", "Yislen Santini"]
venue: "FONDECYT"
tipo: "Revista"
categories: 2024
keywords: ["2024", "FONDECYT", "Relación familia-escuela", "Relación educativa intercultural", "Educación indígena", "Relaciones de poder", "Contexto indígena"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/ART_8 EDUC_PESQUISA_ARIAS_OTROS_2024_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}, {{< meta autores.3 >}}, {{< meta autores.4 >}}  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El  artículo  expone  resultados  de  investigación  sobre  el  sentido  de  la  educación  escolar  desde la perspectiva de los actores del medio educativo y social. El objetivo es dar cuenta de los desafíos de la relación familia-escuela en contexto indígena, desde la perspectiva de los profesores de dos escuelas rurales situadas en comunidades mapuches de La Araucanía, Chile. El problema de investigación plantea que en la educación escolar en contexto mapuche la vinculación familia-escuela, históricamente, se ha caracterizado por relaciones de poder, que niegan la participación de la familia en los procesos de gestión escolar intercultural. De esta manera, se asume una participación funcionalista articulada a aspectos administrativos. La metodología es cualitativa con un nivel de alcance descriptivo, los participantes son seis profesores. El instrumento de recolección de información es la entrevista semidirigida, la técnica de análisis de la información es el análisis de contenido en complementariedad con la teoría fundamentada. Los principales resultados dan cuenta de relaciones de poder que persisten en la relación familia-escuela en contexto mapuche sustentados en una relación de racismo y discriminación. Las principales conclusiones relevan la urgencia de establecer una  formación  continua  sobre  interculturalidad  para  los  actores  del  medio  educativo,  lo  que  permitiría  revertir  las  prácticas  discriminatorias  hacia  “lo  mapuche”  presentes  en  la  escuela.  Esto,  en  contexto  mapuche  permitiría  fortalecer  las  relaciones  educativas  entre  familia  indígena  y  escuela  con  base  en  la  incorporación  de  los  saberes  y  conocimientos  educativos indígenas, contribuyendo en una educación escolar en perspectiva intercultural.   


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```
