---
name: "Desafíos de la educación emocional en el sistema educativo escolar chileno"
title: "Desafíos de la educación emocional en el sistema educativo escolar chileno" 
autores: ["Camila Fernández", "Camila Tripailaf", "Katerin Arias-Ortega"]
venue: "RMIE"
tipo: "Revista"
categories: 2022
keywords: ["2022", "REXE", "Currículum Escolar", "Educación Emocional", "Enseñanza y Aprendizaje"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/ART_14_REXE_TRIPAILAF_ET AL_2022_SCIELO.pdf"
---
**Autores**: {{< meta autores.1 >}}, {{< meta autores.2 >}}, [{{< meta autores.3 >}}](../members/current/Katerin Arias-Ortega.qmd)  
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: En este artículo se presenta un análisis que problematiza los principales desafíos del sistema educativo escolar chileno, para incorporar la educación emocional desde primero a sexto año de Educación Básica en su currículum escolar. La metodología es cualitativa, de tipo descriptivo y corresponde a una revisión documental de las Bases Curriculares de nueve asignaturas del currículum escolar chileno. La técnica de análisis de la información es el análisis de contenido, mediante el cual se buscan develar los núcleos de sentido explícitos e implícitos sobre la educación emocional en la educación escolar. Los principales resultados permiten sostener que en el currículum escolar chileno predomina una invisibilización transversal del desarrollo de la educación emocional en sus contenidos escolares y, por consecuencia, en los procesos de enseñanza y aprendizaje. Concluimos en la urgencia de repensar los currículos escolares, para así poder avanzar en la incorporación de la educación emocional, lo que favorecería el éxito escolar y educativo de todos los estudiantes.


**BibTeX**:
```bibtex
@article{arias2022docencia,
  author = {Arias, Katerin and Del Pino, Miguel and Muñoz, Gerardo},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {21},
  number = {47},
  pages = {12-31},
  doi = {https://doi.org/10.21703/0718-5162202202102147015}
}
```
