---
name: "Desafíos Académicos y Socio-Afectivos de Estudiantes Rurales en la Universidad"
title: "Desafíos Académicos y Socio-Afectivos de Estudiantes Rurales en la Universidad"
autores: ["Katerin Arias", "Tamara Cifuentes", "Francisca Toro", "Leticia Huaiquipan"]
venue: "Caderno CrH"
tipo: "Revista"
categories: 2024
keywords: ["2024", "Caderno CrH", "Ruralidad", "Desafíos Académicos", "Desafíos Socio-Afectivos"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/ART_9 CRH_ARIAS ET AL_2024_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}, {{< meta autores.3 >}}, {{< meta autores.4 >}}    
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo tiene como objetivo exponer los principales desafíos académicos y socio-afectivos que enfrentan estudiantes de sectores rurales en los primeros años de Educación Superior en La Araucanía, Chile. La metodología de investigación es cualitativa de tipo descriptivo, sustentada en un paradigma interpretativo. El instrumento de recolección de datos es la entrevista semi-dirigida. El procedimiento de análisis de los datos se sustenta en la teoría fundamentada a través de una codificación abierta y axial. Los resultados dan cuenta que los estudiantes de sectores rurales tienen mayores dificultades académicas producto de una baja cobertura curricular en la educación media, lo que incide negativamente en su proceso de formación profesional. Además, enfrentan desafíos socio-afectivos que se relacionan con sentimiento de soledad, dificultades en la adaptabilidad al contexto urbanizado y el alejamiento del medio familiar.


**BibTeX**:
```bibtex
@article{arias2024desafios,
  author = {Arias, Katerin and Cifuentes, Tamara and Toro, Francisca and Huaiquipan, Leticia},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {37},
  number = {},
  pages = {1-18},
  doi = {http://dx.doi.org/10.9771/ccrh.v37i0.36685}
}
```
