---
name: "Didáctica Intercultural para las Ciencias Naturales"
title: "Didáctica Intercultural para las Ciencias Naturales" 
autores: ["Viviana Villarroel Cárdenas", "Katerin Arias-Ortega", "Segundo Quintriqueo Millán"]
venue: "Investigações em Ensino de Ciências"
tipo: "Revista"
categories: 2022
keywords: ["2022", "Investigações em Ensino de Ciências", "Educación Intercultural", "Enseñanza de las Ciencias", "Educación Cultural y Responsable", "Hegemonía Cultural", "Educación Escolar"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/ART_11_Didactica para las ciencias_Villarroel_Arias et al_2022_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Viviana Villarroel Cárdenas.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd), [{{< meta autores.3 >}}](../members/current/Segundo Quintriqueo Millán.qmd)  
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo problematiza la didáctica utilizada para la enseñanza de las Ciencias Naturales en situación de diversidad social y cultural en contexto mapuche. La metodología utilizada es una revisión documental-descriptiva de la literatura científica, normativa y divulgación sobre la didáctica intercultural a fin de sistematizar contenidos educativos indígenas que contribuyan y aporten a los procesos de enseñanza-aprendizaje en el sistema educativo escolar chileno. El objetivo es indagar cómo los saberes educativos indígenas pueden contribuir a la enseñanza de las ciencias naturales desde una didáctica intercultural. Los principales resultados evidencian que existen conocimientos educativos indígenas susceptibles de incorporar a la educación escolar y sustentar una didáctica intercultural para la enseñanza de las Ciencias Naturales, lo que permitiría el aprendizaje de todos los estudiantes indígenas y no indígenas. Además, se devela la necesidad de formación continua y capacitación para los docentes en ejercicio profesional y en formación inicial docente sobre los principios de la pedagogía y educación indígena. Proponemos lo anterior, como una estrategia que permita la articulación de saberes y conocimientos educativos indígenas y escolares, para ofrecer procesos de escolarización desde un enfoque educativo intercultural.


**BibTeX**:
```bibtex
@article{villarroel2022didactica,
  author = {Villarroel, Viviana and Arias, Katerin and Quintriqueo, Segundo},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {27},
  number = {2},
  pages = {243-256},
  doi = {10.22600/1518-8795.ienci2022v27n2p243}
}
```
