---
name: "Diferencias Epistemológicas entre la Educación de los Pueblos Originarios con la Educación Escolar en Latinoamérica"
title: "Diferencias Epistemológicas entre la Educación de los Pueblos Originarios con la Educación Escolar en Latinoamérica"
autores: ["Gerardo Fuentes", "Segundo Quintriqueo Millán"]
libro: "Prácticas pedagógicas y educación intercultural: desafíos epistemológicos para la escolaridad en contextos indígenas"
capitulo: "1"
tipo: "Capítulo de Libro"
categories: 2023
keywords: ["2023", "Capítulo de Libro", "Epistemología", "Interculturalidad", "Educación Intercultural", "Educación Indígena", "Educación Intercultural Bilingüe"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/CAP_LIBRO_ARIAS_VILLARROEL_2023.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Segundo Quintriqueo Millán.qmd)    
**Libro**: {{< meta libro >}}   
**Capítulo**: {{< meta capitulo >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: La diversidad sociocultural es una característica de Latinoamérica, puesto que, existen diferentes pueblos originarios con identidad, conocimientos y prácticas singulares, lo que ha permeado al contexto educativo. En base al problema de la educación escolar caracterizada por homogeneizar a los estudiantes en la episteme eurocéntrica occidental, surge el objetivo de discutir las diferencias epistémicas de la educación escolar y la educación de los pueblos originarios de Latinoamérica. El método de este capítulo consiste en una revisión bibliográfica de la literatura científica, normativa y divulgación científica, para develar y contrastar las diferencias epistemológicas con referentes teóricos y estudios acerca del estado del arte asociado a los conocimientos occidentales e indígenas en el marco del sistema educativo escolar. En conclusión, uno de los desafíos de la educación escolar es implementar estrategias que contribuyan a la integración de los saberes indígenas con los saberes occidentales, para lograr que el proceso de enseñanza y aprendizaje sea contextualizado y pertinente a la sociedad y cultura de los estudiantes.


**BibTeX**:
```bibtex
@incollection{fuentes2024diferencias,
  author = {Fuentes, Gerardo and Quintriqueo, Segundo},
  title = {{< meta title >}},
  booktitle = {{< meta libro >}},
  editor = {Dr. Gerardo Andrés Fuentes Vilugrón},
  publisher = {Doctorado en Educación en Consorcio, Universidad Católica de Temuco},
  year = {{< meta categories.1 >}},
  chapter = {{< meta capitulo >}},
  pages = {19-46},
  address = {Doctorado en Educación en Consorcio, Universidad Católica de Temuco}
}
```
