---
name: "Dispossession of Indigenous Knowledge in the Chilean Education System: Mapuche Experiences in Chile"
title: "Dispossession of Indigenous Knowledge in the Chilean Education System: Mapuche Experiences in Chile"
autores: ["Viviana Villarroel Cárdenas", "Katerin Arias-Ortega", "Carlos Sanhueza"]
venue: "Journal of Latinos and Education"
tipo: "Revista"
categories: 2023
keywords: ["2023", "Journal of Latinos and Education", "Dispossession", "Indigenous Knowledge", "School Education", "Epistemicide"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/ART_12_ Dispossession of Indigenous Knowledge_WOS_2023.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Viviana Villarroel Cárdenas.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd), {{< meta autores.3 >}}   
**Lugar de publicación**: {{< meta venue >}}    
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Link**: [Link](https://doi.org/10.1080/15348431.2023.2276782)     
**Resumen**: The article reports on the dispossession of indigenous knowledge in the public education system in Mapuche territory in La Araucanía, a southern region in Chile. The methodology is qualitative, 18 people were interviewed including Mapuche wise men and women, fathers, and mothers who experienced schooling processes in their younger years. The information analysis technique is content analysis, to identify explicit and latent meanings related to the schools they attended and the Chilean education system. Mapuche wise people and parents were consulted on the pedagogical practices of dispossession of ancestral knowledge that have been institutionalized. Main results show that schools have transmitted a Western Eurocentric-based knowledge which results in the dispossession of their own episteme and in their transformation into ordinary Chilean citizens who are unaware of their language and culture as a central axis of their sociocultural identity. Main conclusions account for the historical processes of schooling in an indigenous context, highlighting the consequences that this monocultural education has brought to families, communities, and new generations of indigenous. This poses the challenge of transforming the school curriculum, to transmit their truth, to advance in justice, reparation, and to ensure the non-repetition of the epistemicide of indigenous knowledge in the school.


**BibTeX**:
```bibtex
@article{villarroel2023dispossession,
  author = {Villarroel, Viviana and Arias, Katerin and Sanhueza, Carlos},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {},
  number = {},
  pages = {13},
  doi = {https://doi.org/10.1080/15348431.2023.2276782}
}
```
