---
name: "Educación superior en contexto mapuche: El caso de La Araucanía, Chile"
title: "Educación superior en contexto mapuche: El caso de La Araucanía, Chile"
autores: ["Katerin Arias", "Segundo Quintriqueo"]
venue: "Educare"
categories: ["2020", "Educare", "Educación superior", "Epistemología pluralista", "Interculturalidad", "Racismo científico"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2020_KARIAS/ANEXO_N°3_Art_3_Arias-Ortega y Quintriqueo_ Revista Electrónica Educare_ Scopus_Publicado_2020.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/katerinarias.qmd), [{{< meta autores.2 >}}](../members/current/segundoquintriqueo.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Categorias**: [{{< meta categories.1 >}}](../publications.qmd#category=2024), [{{< meta categories.2 >}}](../publications.qmd#category=Educare), [{{< meta categories.3 >}}](../publications.qmd#category=Educación+superior), [{{< meta categories.4 >}}](../publications.qmd#category=Epistemología+pluralista), [{{< meta categories.5 >}}](../publications.qmd#category=Interculturalidad), [{{< meta categories.6 >}}](../publications.qmd#category=Racismo+científico)  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El artículo analiza la educación superior en Chile en contexto mapuche, específicamente en La Araucanía. El método utilizado es un análisis y discusión bibliográfica que considera 4 libros de referencia, 17 artículos científicos y 8 documentos normativos, sobre educación superior en contexto indígena. La tesis plantea que la educación superior está arraigada a un racismo científico institucional que no incorpora la episteme indígena en la formación y construcción de conocimientos de estudiantes mapuches y no mapuches. Concluimos que el racismo científico en la educación superior trae consecuencias como bajos resultados académicos, debido a la descontextualización curricular. También, mantiene y perpetúa las desigualdades sociales, académicas, políticas y económicas en el contexto regional, desvaloriza lo propio y valora lo ajeno.  


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```