---
name: "Educación intercultural articulada a la espisteme indígena en latinoamerida. El caso mapuche en chile"
title: "Educación intercultural articulada a la espisteme indígena en latinoamerida. El caso mapuche en chile"
autores: ["Segundo Quintriqueo", "Katerin Arias"]
venue: "FONDECYT"
tipo: "Revista"
categories: 2019
keywords: ["2019", "FONDECYT", "Educación intercultural", "Episteme indígena", "Formación inicial docente"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2019_KARIAS/ART_4_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El  artículo  discute  experiencias  de  educación  intercultural  articulada  a  la  episteme  indígena,  particularmente  el  caso  mapuche  en Chile. En contexto de colonización, se ha desarrollado un sistema de educación escolar y formación del profesorado, funda-mentado en la colonialidad del saber y del poder que limita a los profesores la toma de consciencia del valor de otras epistemes, para comprender la educación escolar en perspectiva intercultural. La metodología empleada es la investigación educativa y un procedimiento de análisis de contenido. Como resultado planteamos que la interculturalidad es una propuesta ética, epistémica y política, para construir sociedades democráticas que reconozcan las diferentes sociedades y culturas que cohabitan en contextos de colonización. Así, la formación inicial y continua de los profesores, debiera favorecer la adquisición de competencias didácticas fundamentadas en la episteme indígena. Discutimos y concluimos que: 1) la educación intercultural articulada a la episteme indígena es pertinente y factible de abordar, desde un enfoque educativo intercultural; 2) la pedagogía y educación indígena constituyen un aporte para sustentar un currículum escolar intercultural; y 3) la educación desde un pluralismo epistemológico, nos plantea el desafío de establecer una relación cercana con los actores del medio educativo y social en contexto indígena.   


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```
