---
name: "Escuelas en Territorio Mapuche: desigualdades en el contexto chileno"
title: "Escuelas en Territorio Mapuche: desigualdades en el contexto chileno"
autores: ["Katerin Arias", "Fernando Peña", "Segundo Quintriqueo", "Elías Andrade"]
venue: "Revista Brasileira de Educação"
categories: 2020
tipo: "Revista"
keywords: ["2020", "Revista Brasileira de Educação", "Resultados Sistema de Medición de la Calidad de la Educación", "Escuelas municipales y particulares subvencionadas", "Educación rural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2020_KARIAS/ANEXO_N°2_Art_2_Arias-Ortega, Peña-Cortés_Quintriqueo y Andrade_ Revista Brasileira de Educação_Q3_ Scopus_Publicado_2020.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}, [{{< meta autores.3 >}}](../members/current/Segundo Quintriqueo.qmd), {{< meta autores.4 >}}  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El artículo presenta un estudio exploratorio sobre resultados en la prueba de evaluación del Sistema de Medición de la Calidad de la Educación en comprensión lectora, durante los años 2011 al 2015, en La Araucanía, Chile. Metodológicamente, se describen los resultados obtenidos por una muestra de 22 escuelas emplazadas en comunidades Mapuches. Los resultados dan cuenta que las escuelas municipales rurales, obtienen mejores resultados respecto a las escuelas particulares subvencionadas con una diferencia de 8 a 10 puntos. Esto es relevante, porque en comunidades Mapuches existe una supremacía de escuelas particulares subvencionadas, que sistemáticamente obtienen bajos puntajes, lo que continuaría perpetuando las desigualdades sociales y educativas en el territorio entre Mapuches y no Mapuches.  


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```
