---
name: "Essential Mapuche knowledge for an effective intercultural school education: perspectives of traditional educators"
title: "Essential Mapuche knowledge for an effective intercultural school education: perspectives of traditional educators"
autores: ["Katerin Arias", "Carlo Previl"]
venue: "Journal of Multilingual and Multicultural Development" 
tipo: "Revista"
categories: 2023
keywords: ["2023", "Journal of Multilingual and Multicultural Development", "Indigenous Knowledge", "Sociocultural Practices", "Indigenous Spirituality", "Intercultural Education", "Relational Ontology"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/ART_6_JMID_Essential Mapuche_ARIAS_WOS_2023.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}   
**Lugar de publicación**: {{< meta venue >}}    
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: This article presents traditional Mapuche knowledge that has been identified as essential in the pedagogical practices of several traditional educators (Kimche) in implementing the bilingual intercultural education program (PEIB) in Chile. This research is qualitative, and the semi-directed interview is used for gathering information. The information analysis technique is thematic analysis. The main results identify expressions of traditional Mapuche knowledge categorized based on sociocultural practices and spirituality. This knowledge, which is present in the social memory of the Kimche, is considered an essential part of their pedagogical practices to ensure cultural and territorial identity. We conclude that there is a challenge involved in incorporating this knowledge of the indigenous cosmogony and its experiential dimensions within the framework of the PEIB. This knowledge forms the basis of Mapuche experiential and community education, through which it is possible to strengthen the intercultural formation of children and young people by learning indigenous languages and cultures. The intercultural approach promotes a gateway towards engaging indigenous knowledge with contents of the school curriculum that reinforces the sociocultural identity of children through their social practices coherently with the educational pillars defined by UNESCO.


**BibTeX**:
```bibtex
@article{arias2023essential,
  author = {Arias, Katerin and Previl, Carlo},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {88},
  number = {},
  pages = {349-369},
  doi = {10.1080/01434632.2023.2219235}
}
```
