---
name: "Etnografía escolar sobre la educación intercultural en tres escuelas mapuches de La Araucanía"
title: "Etnografía escolar sobre la educación intercultural en tres escuelas mapuches de La Araucanía"
autores: ["Katerin Arias-Ortega"]
venue: "Educar em Revista"
tipo: "Revista"
categories: 2021
keywords: ["2021", "Educar em Revista", "Educación Intercultural Bilingüe", "Relación educativa", "Interculturalidad"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2021_KARIAS/ART_N°5_ ARIAS-ORTEGA_educaremrevista_2021_WOS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: La política educativa del Estado chileno desde el año 1996 implementa el Programa de Educación Intercultural Bilingüe (PEIB), como una forma de responder a las demandas educativas del pueblo mapuche, incorporando al currículo escolar el aprendizaje de contenidos sobre la lengua y la cultura de dicho pueblo. El artículo expone resultados de investigación sobre la implementación del PEIB en tres escuelas de La Araucanía. La metodología es de carácter cualitativo, con un nivel descriptivo de alcance exploratorio. La conclusión es que existe una distancia entre el discurso oficial sobre la implementación del PEIB y realidades educativas mapuches que demandan explícitamente una relación más simétrica entre el profesor mentor y el educador tradicional y los estudiantes. Concluimos que la EIB, aun cuando lleva más de veinte años en el sistema escolar chileno, no estaría contribuyendo al desarrollo de bilingüismo aditivo, mediante el reaprendizaje de la lengua indígena.


**BibTeX**:
```bibtex
@article{arias2021etnografia,
  author = {Arias-Ortega, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {volumen},
  number = {número},
  pages = {23},
  doi = {http://dx.doi.org/10.1590/0104-4060.70098}
}
```
