---
name: "Evaluación continua del profesorado: ética intercultural para una educación con pertinencia sociocultural indígena"
title: "Evaluación continua del profesorado: ética intercultural para una educación con pertinencia sociocultural indígena"
autores: ["Susana Oñate", "Katerin Arias-Ortega"]
venue: "Meta: Avaliação"
tipo: "Revista"
categories: 2023
keywords: ["2023", "Meta: Avaliação", "Evaluación", "Profesorado", "Educación Intercultural", "Ética Intercultural", "Discriminación"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/ART_10_REVMETA_OÑATE_ARIAS_SCOPUS_2023.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd)   
**Lugar de publicación**: {{< meta venue >}}    
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El ensayo discute sobre la necesidad de incorporar en las políticas educativas chilenas, criterios para una evaluación ética del profesorado en contextos educativos interculturales. Se analizan las características de las políticas actuales de evaluación del profesorado chileno, con base en propuestas teóricas que problematizan la necesidad de una formación ética intercultural para promover una cultura escolar que incorpore la cultura indígena local. Los principales resultados dan cuenta de la urgencia de pensar una competencia de ética intercultural en la formación del profesorado, lo que se debe fortalecer por medio de una política de evaluación continua de las competencias adquiridas. Se concluye con la propuesta de siete criterios de evaluación para el desarrollo de una actuación ética intercultural, para repensar una educación con pertinencia sociocultural indígena.


**BibTeX**:
```bibtex
@article{onate2023evaluacion,
  author = {Oñate, Susana and Arias, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {15},
  number = {48},
  pages = {669-693},
  doi = {http://dx.doi.org/10.22347/2175-2753v15i48.4073}
}
```
