---
name: "Implicancias de la sociedad y cultura hegemónica en la educación escolar en contexto mapuche (Chile): una crítica epistemológica"
title: "Implicancias de la sociedad y cultura hegemónica en la educación escolar en contexto mapuche (Chile): una crítica epistemológica"
autores: ["Katerin Arias", "Eliana Ortiz-Velosa"]
venue: "FONDECYT"
categories: ["2019", "Espacios", "Sociedad y cultura", "Educación escolar en contexto mapuche", "Interculturalidad"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2019_KARIAS/ART_2_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/katerinarias.qmd), {{< meta autores.2 >}}  
**Lugar de publicación**: {{< meta venue >}}   
**Categorias**: [{{< meta categories.1 >}}](../publications.qmd#category=2019), [{{< meta categories.2 >}}](../publications.qmd#category=Espacios), [{{< meta categories.3 >}}](../publications.qmd#category=Sociedad+y+cultura), [{{< meta categories.4 >}}](../publications.qmd#category=Educación+escolar+en+contexto+mapuche), [{{< meta categories.5 >}}](../publications.qmd#category=Interculturalidad)  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El artículo propone un enfoque epistemológico crítico de la implicación de la sociedad y cultura hegemónicas en la educación escolar de niños mapuche en contextos indígenas e interculturales en La Araucanía, Chile. El enfoque teórico metodológico que sustenta nuestro estudio es la sociología de la educación, desde autores clásicos, neoclásicos y actuales. Los resultados proporcionan un estado del arte en los conceptos principales como una posibilidad para el estudio de la educación y su conexión con los procesos de transformación social.   


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```