---
name: "Interculturalidad en educación superior: experiencia en educación inicial en La Araucanía, Chile"
title: "Interculturalidad en educación superior: experiencia en educación inicial en La Araucanía, Chile"
autores: ["Soledad Morales-Saavedra", "Segundo Quintriqueo", "Pilar Uribe-Sepulveda", "Katerin Arias"]
venue: "Convergencia"
categories: 2018
tipo: "Revista"
keywords: ["2018", "Convergencia", "Interculturalidad", "Enfoque Educativo Intercultural", "Formación inicial docente", "Educación e infancia", "Conocimientos educativos mapuches"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2018_KARIAS/ART_2_SCOPUS.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Segundo Quintriqueo.qmd), {{< meta autores.3 >}}, [{{< meta autores.4 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**:  El objetivo del artículo es presentar resultados de la experiencia desarrollada en los procesos de formación inicial docente. La investigación sostiene como supuesto que en las familias y comunidades indígenas mapuches presentes en Chile existen conocimientos asociados a prácticas socioculturales, que permitirían sustentar una Educación Parvularia, desde un enfoque educativo intercultural, con base epistémica en la memoria social de padres y sabios. Los principales resultados develan temas claves en la formación, respecto a los saberes para una educación intercultural para niños menores de seis años, fortaleciendo la comunicación y trabajo con la familia y la comunidad.  


**BibTeX**:
```bibtex
@article{morales2018interculturalidad,
  author = {Morales-Saavedra, Soledad and Quintriqueo, Segundo and Uribe-Sepulveda, Pilar and Arias, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {volumen},
  number = {número},
  pages = {rango de páginas},
  doi = {DOI}
}
```
