---
name: "Intégrer la nordicité dans l'éducation et la formation: exploration d'enjeux"
title: "Intégrer la nordicité dans l'éducation et la formation: exploration d'enjeux"
autores: ["Carlo Prévil", "Katerin Arias-Ortega"]
venue: "Congrès d'Études Inuit 2019"
tipo: "Revista"
categories: 2021
keywords: ["2021", "Congrès d'Études Inuit"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2021_KARIAS/ART_N°7_ OTRO Y ARIAS-ORTEGA_Cap_ libro_2021_REFERATO EXTERNO_CANADA.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: Les études sur la nordicité semblent avoir pris un essor considérable dans l'ensemble des agendas fédéraux et provinciaux depuis le tournant du millénaire. Pourtant, il est permis de se questionner sur un certain décalage et même d'un retard pour la prise en charge de l'éducation au Nord dans la géographie scolaire. Historiquement, la géographie scolaire a très peu considéré la pertinence d'inclure les connaissances sur le Nord comme des contenus à faire apprendre pour l'éducation au lieu dans les programmes scolaires. Le Nord est principalement considéré comme un réservoir de ressources naturelles. Toutefois, les territoires du Nord sont également porteurs de complexités culturelles et socioécologiques, puisque les imaginaires, les identités et les cultures véhiculées par ces lieux peuvent s'inscrire dans des perspectives distinctes, voire antagonistes, selon les groupes d'intérêt ou les communautés de pratiques en présence. Tout ceci constitue de nouveaux enjeux interpellant les finalités de l'éducation et la formation sur le monde social. Cet article discute l'opportunité de réfléchir sur les processus de production de nouveaux savoirs à faire apprendre sur le Nord dans l'éducation et la formation au Québec et au Canada. Les lieux du Nord autant que les communautés qui les convoitent font face à des transformations socioterritoriales de divers ordres dans le temps, dans l'espace et dans leurs valeurs respectives, et tout ceci dans un monde qui change. Nous concevons de cette exploration une réelle opportunité pour la recomposition disciplinaire de la géographie scolaire.


**BibTeX**:
```bibtex
@article{previl2021integrer,
  author = {Prévil, Carlo and Arias-Ortega, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {volumen},
  number = {número},
  pages = {146-161},
  doi = {DOI}
}
```
