---
name: "Le sens du Nord dans l’éducation et la formation au lieu : Exploration d’enjeux"
title: "Le sens du Nord dans l’éducation et la formation au lieu : Exploration d’enjeux"
autores: ["Carlo Prévil", "Katerin Arias-Ortega"]
venue: "Éducation relative à l'environnement"
tipo: "Revista"
categories: 2021
keywords: ["2021", "Éducation relative à l'environnement", "Sense of Place", "Geographic Education", "Place Based Education", "Interculturalism", "Eco-Citizenship"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2021_KARIAS/ART_N°8_ OTRO_ARIAS-ORTEGA_ERE_2021_OTRAS INDEX.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Katerin Arias.qmd)    
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: Les études sur la nordicité ont pris un essor considérable dans l'ensemble des agendas fédéraux et provinciaux depuis le tournant du millénaire au Canada. Toutefois, il est permis de se questionner sur le retard de l'éducation et de la formation en géographie au Québec, à s'intéresser au sens du Nord. Historiquement, l'éducation formelle a très peu considéré en effet les connaissances issues des communautés nordiques. Cet article examine la conceptualisation de nouveaux savoirs sur le sens du Nord comme sens du lieu (sense of place) au Québec et au Canada. L'élaboration de savoirs essentiels à enseigner et de compétences à développer sur le Nord peut constituer une réelle opportunité pour le renouvellement de l'éducation géographique et de l'éducation relative à l'environnement. Un tel renouvellement pourra contribuer à promouvoir l'écocitoyenneté dans la perspective du développement d'identités territoriales et culturelles, et de la prise en compte de nouvelles dynamiques spatiales d'humanisation.


**BibTeX**:
```bibtex
@article{previl2021integrer,
  author = {Prévil, Carlo and Arias-Ortega, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {16},
  number = {2},
  pages = {22},
  doi = {10.4000/ere.7813}
}
```
