---
name: "Manual de aplicación - Modelo de Intervención Educativa Intercultural en Contexto Indígena"
title: "Manual de aplicación - Modelo de Intervención Educativa Intercultural en Contexto Indígena"
autores: ["Segundo Quintriqueo", "Daniel Quilaqueo"]
libro: "Manual de aplicación - Modelo de Intervención Educativa Intercultural en Contexto Indígena"
capitulo: "All"
categories: ["2019", "Libro", "Educación Intercultural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2019_KARIAS/Manual-de-Intervención-Educativa_2019_lIBRO.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/segundoquintriqueo.qmd), {{< meta autores.2 >}}  
**Libro**: {{< meta libro >}}   
**Capítulo**: {{< meta capitulo >}}   
**Categorias**: [{{< meta categories.1 >}}](../publications.qmd#category=2024), [{{< meta categories.2 >}}](../publications.qmd#category=Libro), [{{< meta categories.3 >}}](../publications.qmd#category=Educación+Intercultural) 
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El problema que se busca solucionar mediante el Modelo de Intervención Educativa Intercultural en Contexto Indígena, es el desconocimiento de los saberes y conocimientos educativos mapuches, por parte de los profesores que se desempeñan en contextos de comunidades indígenas. Precisamos que el contexto indígena está delimitado a los territorios históricamente habitados por pueblos originarios colonizados por grupos hegemónicos de origen eurocéntrico occidental: españoles, franceses, ingleses y portugueses en América. En esta perspectiva, las colectividades históricas, personas originarias, que viven tanto en contexto rural como urbano,  constituyen  comunidades  indígenas.  Este  es  el  caso  de  las comunidades mapuches, que viven en la región Macro Centro Sur de Chile.   


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  book = {{< meta libro >}},
  year = {{< meta categories.1 >}},
}
```