---
name: "Monoculturalidad en las prácticas pedagógicas en la formación inicial docente en La Araucanía, Chile"
title: "Monoculturalidad en las prácticas pedagógicas en la formación inicial docente en La Araucanía, Chile"
autores: ["Katerin Arias", "Segundo Quintriqueo", "Vanessa Valdebenito"]
venue: "FONDECYT"
categories: ["2018", "FONDECYT", "Prácticas pedagógicas", "Monoculturalidad", "Formación inicial docente", "Enfoque educativo intercultural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2018_KARIAS/ART_1_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/katerinarias.qmd), [{{< meta autores.2 >}}](../members/current/segundoquintriqueo.qmd), {{< meta autores.3 >}}  
**Lugar de publicación**: {{< meta venue >}}   
**Categorias**: [{{< meta categories.1 >}}](../publications.qmd#category=2018), [{{< meta categories.2 >}}](../publications.qmd#category=FONDECYT), [{{< meta categories.3 >}}](../publications.qmd#category=Prácticas+pedagógicas), [{{< meta categories.4 >}}](../publications.qmd#category=Monoculturalidad), [{{< meta categories.5 >}}](../publications.qmd#category=Formación+inicial+docente), [{{< meta categories.6 >}}](../publications.qmd#category=Enfoque+educativo+intercultural)  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**:  El tema central del artículo se relaciona con las prácticas pedagógicas monoculturales en la formación inicial docente y el sistema educativo escolar. El problema que se aborda es la descontextualización curricular en la formación inicial docente. El objetivo es analizar la monoculturalidad de prácticas arraigadas a métodos y contenidos ezrocéntricos occidentales, producto del legado colonial y poscolonial en Chile. La metodología consistió en una revisión de la literatura normativa y científica a nivel nacional e internacional, para lograr una comprensión y explicación del problema de la monoculturalidad en las prácticas pedagógicas. Los principales resultados aportan un estado del arte sobre el desarrollo histórico de la educación en contexto indígena e intercultural, donde se evidencia el desarrollo de prácticas pedagógicas monoculturales de manera transversal en los niveles del sistema educativo chileno. El ensayo propone algunas pistas de acción para transformar la formación inicial de profesores, a través del enfoque educativo intercultural y competencias comunicativas interculturales, con el fin de superar la monoculturalidad, el racismo hacia las personas indígenas, tanto en el medio escolar como social. Se concluye que: 1. la monoculturalidad persiste como una práctica en la formación inicial docente, lo que trae como consecuencia el desconocimiento del contexto social y cultural de los estudiantes, tanto en los formadores de profesores como en los futuros profesores; y 2. la educación escolar continúa con la transmisión de prejuicios y la construcción de actitudes racistas, perpetuando el racismo institucionalizado en contextos indígenas e interculturales.  


**BibTeX**:
```bibtex
@article{example,
  title = {{< meta title >}},
  author = {{< meta autores.1 >}} and {{< meta autores.2 >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
}
```