---
name: "Percepciones de estudiantes de enseñanza básica sobre la educación intercultural bilingüe en La Araucanía, Chile"
title: "Percepciones de estudiantes de enseñanza básica sobre la educación intercultural bilingüe en La Araucanía, Chile"
autores: ["Albert Wyss", "Jorge Pacheco", "Katerin Arias"]
venue: "REXE"
tipo: "Revista"
categories: 2021
keywords: ["2021", "REXE", "Educación intercultural bilingüe", "lengua indígena", "cultura indígena", "percepción"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2021_KARIAS/ART_N°6_OTROS Y ARIAS-ORTEGA_REXE_2021_SCIELO.pdf"
---
**Autores**: {{< meta autores.1 >}}, {{< meta autores.2 >}}, [{{< meta autores.3 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})  
**Resumen**: El artículo expone los resultados de investigación respecto de las percepciones de estudiantes de primero a sexto año básico sobre la educación intercultural bilingüe (EIB) en una escuela rural de La Araucanía. La metodología es cualitativa. El instrumento de recolección de datos es la entrevista semi dirigida y el uso de narrativas de experiencias por parte del último. La técnica de análisis de contenido es complementada con la teoría fundamentada. Los principales resultados dan cuenta que existe una baja motivación por parte de los estudiantes para aprender la lengua y la cultura mapuche, producto del racismo sistémico que ha existido hacia lo indígena en la sociedad en general y en la escuela en particular. A su vez, se evidencia que el aprendizaje de la lengua mapuche se realiza principalmente a través de la comunicación verbal y no verbal tanto de los padres, profesores y pares en el ámbito educativo. Las principales conclusiones nos permiten evidenciar que: 1) los estudiantes muestran disposición favorable respecto a tener un profesor mapuche; 2) el bajo dominio de la lengua por parte de los estudiantes y el poco uso de la lengua en situaciones de la vida cotidiana inciden negativamente en la predisposición para aprender la lengua; y 3) la sensibilización de los padres (alfabetización cultural) es necesaria y contribuye a mejorar la disposición de los estudiantes hacia el aprendizaje de la lengua y cultura mapuche.


**BibTeX**:
```bibtex
@article{wyss2021percepciones,
  author = {Wyss, Albert and Pacheco, Jorge and Arias, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {volumen},
  number = {número},
  pages = {167-181},
  doi = {https://doi.org/10.21703/rexe.20212042wyss10}
}
```
