---
name: "Pluralismo Epistemológico como Posibilidad para Superar Desacuerdos Epistemológicos en la Educación Intercultural en Contexto Mapuche"
title: "Pluralismo Epistemológico como Posibilidad para Superar Desacuerdos Epistemológicos en la Educación Intercultural en Contexto Mapuche"
autores: ["Segundo Quintriqueo Millán", "Katerin Arias-Ortega"]
libro: "Lineamientos Estratégicos para la Implementación de la Educación Intercultural desde un Modelo de Acompañamiento"
capitulo: "1"
tipo: "Capítulo de Libro"
categories: 2024
keywords: ["2024", "Capítulo de Libro", "Pluralismo Epistemológico", "Educación Escolar", "Enfoque Educativo Intercultural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/Cap_libro_2Arias-Ortega_2024_Referato.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo Millán.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd)    
**Libro**: {{< meta libro >}}   
**Capítulo**: {{< meta capitulo >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: Este capítulo discute sobre los problemas de la educación escolar en contexto indígena la que se ha caracterizado, históricamente, por su estructura colonial que ha instalado una educación desigual para indígenas en los ámbitos educativo, social, económico y territorial. Esto ha traído como consecuencia, en los estudiantes indígenas, la negación de su propio lengua, de su cultura y conocimientos en la educación escolar, lo que afecta el desarrollo de su identidad sociocultural y el desarrollo social de las nuevas generaciones con su pueblo. La tesis que sostenemos plantea que el pluralismo epistemológico emerge como una posibilidad para comprender, explicar y superar los desacuerdos epistemológicos en la educación intercultural en contexto mapuche. Esto podría materializarse a través de la incorporación de los principios de pedagogía y educación indígena en la educación escolar, para sensibilizar a los actores del medio educativo y social, sobre la importancia de formar a las nuevas generaciones con arraigo territorial. De esta manera, se estimula el éxito escolar y educativo de todos los estudiantes, indígenas y no indígenas, facilitando su desarrollo desde una perspectiva integral que les entregue las herramientas, saberes, conocimientos y habilidades para desenvolverse adecuadamente, en la episteme mapuche como escolar, desde un pluralismo epistemológico intercultural.


**BibTeX**:
```bibtex
@incollection{quintriqueo2024pluralismo,
  author = {Quintriqueo, Segundo and Arias, Katerin},
  title = {{< meta title >}},
  booktitle = {{< meta libro >}},
  editor = {},
  publisher = {Universidad Católica de Temuco},
  year = {{< meta categories.1 >}},
  chapter = {{< meta capitulo >}},
  pages = {15-},
  address = {Universidad Católica de Temuco}
}
```
