---
name: "Principios de la Pedagogía y Educación Indígena como Base para Implementar la Educación Intercultural Bilingüe"
title: "Principios de la Pedagogía y Educación Indígena como Base para Implementar la Educación Intercultural Bilingüe"
autores: ["Segundo Quintriqueo Millán", "Gerardo Muñoz", "Katerin Arias-Ortega", "Soledad Morales", "Elías Andrade", "Viviana Zapata"]
venue: "Revista Internacional de Educación para la Justicia Social"
tipo: "Revista"
categories: 2023
keywords: ["2023", "Revista Internacional de Educación para la Justicia Social", "Pedagogía", "Educación Indígena", "Bilingüismo", "Descolonización", "Justicia Social"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/ART_13_RIEJS_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo Millán.qmd), {{< meta autores.2 >}}, [{{< meta autores.3 >}}](../members/current/Katerin Arias-Ortega.qmd), {{< meta autores.4 >}}, {{< meta autores.5 >}}, {{< meta autores.6 >}}   
**Lugar de publicación**: {{< meta venue >}}    
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo problematiza sobre los principios de la pedagogía y educación indígena para implementar la educación intercultural bilingüe, como eje articulador entre los conocimientos escolares y los conocimientos mapuches, en el caso de La Araucanía, Chile. La metodología es una revisión teórica de la literatura normativa, científica y de divulgación científica a nivel nacional e internacional. Se utiliza el análisis de contenido, el que permite develar núcleos de contenido de orden abstracto, tanto a nivel explícito como implícito, con el propósito de comprender las prácticas que limitan y/o posibilitan la incorporación de los principios de la pedagogía y educación indígena en la educación escolar. Los principales resultados dan cuenta que en territorios de colonización existen una base de saberes y conocimientos indígenas que permitirían la transversalización de la pedagogía y educación indígena en la educación escolar, para ofrecer una educación intercultural que favorezca la revitalización de la identidad sociocultural de niños indígenas y no indígenas, visibilizando la existencia de un pluralismo epistemológico en territorios indígenas. Concluimos que es urgente incorporar los principios de la pedagogía y educación indígena a la educación escolar.


**BibTeX**:
```bibtex
@article{quintriqueo2023principios,
  author = {Quintriqueo, Segundo and Muñoz, Gerardo and Arias, Katerin and Morales, Soledad and Andrade, Elías and Zapata, Viviana},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {12},
  number = {2},
  pages = {271-287},
  doi = {https://doi.org/10.15366/riejs2023.12.2.015}
}
```
