---
name: "Propuesta Pedagógica Interculturalpara la Implementación de la Asignatura Lengua y Cultura de los Pueblos Originarios Ancestrales"
title: "Propuesta Pedagógica Interculturalpara la Implementación de la Asignatura Lengua y Cultura de los Pueblos Originarios Ancestrales"
autores: ["Segundo Quintriqueo", "Katerin Arias", "Soledad Morales", "Gerardo Muñoz", "Dykssa Saez", "Elias Andrade", "Viviana Zapata", "Viviana Villarroel"]
libro: "Propuesta Pedagógica Interculturalpara la Implementación de la Asignatura Lengua y Cultura de los Pueblos Originarios Ancestrales"
tipo: "Libro"
categories: 2022
keywords: ["2022", "Libro", "Educación Intercultural"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/propuesta pedagógica 2022 WEB (12-4-23).pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.3 >}}, {{< meta autores.4 >}}, {{< meta autores.5 >}}, {{< meta autores.6 >}}, {{< meta autores.7 >}}, [{{< meta autores.8 >}}](../members/current/Viviana Villarroel.qmd)  
**Libro**: {{< meta libro >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}   
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: La propuesta pedagógica intercultural se propone apoyar la implementación de la Asignatura Lengua y Cultura de los Pueblos Originarios Ancestrales, para aportar a la transversalización de la educación intercultural en el sistema educativo escolar chileno. Esto, a través de pistas de acción y estrategias para la contextualización de los contenidos educativos escolares en articulación con el conocimiento indígena, desde un enfoque educativo intercultural.

La propuesta pedagógica considera dos componentes centrales de acción: el medio escolar y el medio social, desde una dimensión teórica, empírica y metodológica.

En la dimensión teórica, las sociedades y culturas poseen contenidos (saberes educativos), métodos (formas de aprender y enseñar) y finalidades educativas (ideal de persona que se busca formar), que son las bases para la educación escolar y familiar.

En la dimensión empírica, los agentes del medio educativo y social transmiten los saberes y conocimientos educativos a las nuevas generaciones, mediante prácticas educativas formales (la educación planificada en la institución escuela), informales (educación que se realiza en la cotidianeidad) y socioculturales (educación como resultado de la socialización, tanto en la escuela como en la familia).

En la dimensión metodológica, tanto en la educación escolar como familiar, existen formas de organizar las preguntas para establecer una relación con el conocimiento educativo y su respectiva transmisión a las nuevas generaciones, a partir de un marco de referencia que se apoya en la ecuación: pasado incorporado, contexto de acción presente y las prácticas educativas observables en el tiempo (Quilaqueo, Quintriqueo, Riquelme y Loncon, 2016).

Dichas dimensiones de la educación en el medio educativo y social, se sustenta desde el triángulo pedagógico, que articula la relación del profesor y/o los/as educadores/as tradicionales con los estudiantes y los contenidos, mediados por la institución escolar, la familia y el marco normativo nacional e internacional que orienta la educación intercultural.


**BibTeX**:
```bibtex
@book{quintriqueo2022propuesta,
  author = {Quintriqueo, Segundo and Arias, Katerin and Morales, Soledad and Muñoz, Gerardo and Saez, Dykssa and Andrade, Elias and Zapata, Viviana and Villarroel, Viviana},
  title = {{< meta title >}},
  publisher = {Centro de Investigación en Educación en Contexto Indígena e Intercultural},
  year = {{< meta categories.1 >}},
  address = {Av. Rudecindo Ortega 02950, Edificio Waldo Marchant, 4º piso},
  edition = {1},
  isbn = {978-956-6224-01-3}
}
```
