---
name: "Relación Educativa Intercultural en Contexto Indígena: Desafíos Epistemológicos en la Escuela Actual"
title: "Relación Educativa Intercultural en Contexto Indígena: Desafíos Epistemológicos en la Escuela Actual"
autores: ["Katerin Arias-Ortega", "Lázaro Blanco"]
venue: "Revista Portuguesa de Educação"
tipo: "Revista"
categories: 2024
keywords: ["2024", "Revista Portuguesa de Educação", "Relación Educativa", "Enfoque Educativo Intercultural", "Interculturalidad"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/ART_13_PORTUGUESA_EDUC_ARIAS ET AL_2024_SCOPUS.pdf"
---
**Autores**: {{< meta autores.1 >}}, [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd)
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo discute la necesidad de repensar las relaciones educativas en contexto indígena, que históricamente se han caracterizado por tensiones epistemológicas entre el profesorado y los estudiantes indígenas, lo que limita dar respuesta a los desafíos de interculturalismo que caracterizan a la escuela y la sociedad actual. Las discusiones se enmarcan en un proceso de análisis e interpretación respaldado por un marco epistémico coherente y sistematizado de fundamentos teóricos como la pedagogía crítica, el constructivismo y el enfoque educativo intercultural. Estos fundamentos teóricos cuestionan la lógica hegemónica atribuida al sentido de la escuela y las relaciones educativas que históricamente han establecido relaciones de poder, asimetría e invisibilización de los marcos epistémicos propios de sujetos que pertenecen a sociedades y culturas diferentes los que han sido negados y minorizados en la educación escolar. De esta manera, sostenemos que repensar las relaciones educativas en contexto indígena desde un enfoque intercultural permitiría avanzar hacia un pluralismo epistemológico en la educación escolar en contextos de diversidad social, cultural y territorial. Concluimos la urgencia de una relación educativa en contexto indígena que permita formar a ciudadanos interculturales como desafíos del siglo XXI caracterizado por la diversidad social y cultural propio de la sociedad global.

**BibTeX**:
```bibtex
@article{arias2024relacion,
  author = {Arias, Katerin and Blanco, Lázaro},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {37},
  number = {2},
  pages = {23},
  doi = {http://doi.org/10.21814/rpe.28453}
}
```
