---
name: "Sentido de la Educación: Aproximación desde la Lógica Escolar y Familiar Mapuche"
title: "Sentido de la Educación: Aproximación desde la Lógica Escolar y Familiar Mapuche"
autores: ["Katerin Arias", "Segundo Quintriqueo"]
libro: "Lineamientos Estratégicos para la Implementación de la Educación Intercultural desde un Modelo de Acompañamiento"
capitulo: "2"
tipo: "Capítulo de Libro"
categories: 2024
keywords: ["2024", "Capítulo de Libro", "Educación Escolar", "Educación Indígena", "Tensiones Epistemológicas"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/Cap_libro_3Arias-Ortega_2024_Referato.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), [{{< meta autores.2 >}}](../members/current/Segundo Quintriqueo.qmd)    
**Libro**: {{< meta libro >}}   
**Capítulo**: {{< meta capitulo >}}   
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: Este capítulo discute los desacuerdos epistemológicos sobre el sentido de la educación desde la lógica escolar y familiar mapuche. Esos desacuerdos se expresan respecto de los contenidos, métodos y finalidades educativas que procura la educación familiar indígena, las que entran en tensión con la educación escolar, en la que prima un aprendizaje alejado de la realidad social y cultural de los niños que allí se educan. Esto ha traído como consecuencia una pérdida progresiva de la identidad sociocultural indígena al considerar sus marcos epistémicos y patrones socioculturales como elementos necesarios de eliminar y/o desarraigar de la educación de las nuevas generaciones de niños y jóvenes indígenas, para transformarlos en ciudadanos chilenos ordinarios. A la vez, ha generado un aislamiento de la familia y comunidad indígena en la educación de sus hijos. Lo anterior, ha incidido en la discontinuidad de la transmisión de los saberes y conocimientos propios desde los principios de la pedagogía y educación indígena hacia sus hijos. Concluimos en la urgencia de una articulación de los saberes y conocimientos educativos indígenas y escolares para repensar el sentido de la escuela en territorio indígena, desde una vinculación de la familia-escuela-comunidad-universidad. Esto permitirá co-construir un sentido compartido de la educación escolar que responda a las necesidades de una educación con pertinencia social, cultural y territorial, desde un pluralismo epistemológico, para reconstruir las relaciones educativas interculturales en el espacio educativo.


**BibTeX**:
```bibtex
@incollection{arias2024sentido,
  author = {Arias, Katerin and Quintriqueo, Segundo},
  title = {{< meta title >}},
  booktitle = {{< meta libro >}},
  editor = {},
  publisher = {Universidad Católica de Temuco},
  year = {{< meta categories.1 >}},
  chapter = {{< meta capitulo >}},
  pages = {31-},
  address = {Universidad Católica de Temuco}
}
```
