---
name: "Sobrecarga de trabajo en tiempos de pandemia: percepción de madres de La Araucanía, Chile"
title: "Sobrecarga de trabajo en tiempos de pandemia: percepción de madres de La Araucanía, Chile"
autores: ["Katerin Arias", "Bárbara Pinto", "Carol Martínez", "María Rodríguez", "Yanira Benítez"]
venue: "Revista Colombiana de Sociología" 
tipo: "Revista"
categories: 2023
keywords: ["2023", "Revista Colombiana de Sociología", "COVID-19", "Enfoque de Género", "Economía del Cuidado", "Mujeres", "Pandemia", "Sobrecarga Laboral"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2023_KARIAS/ART_2_Sobrecarga de trabajo en tiempos de pandemia_ARIAS_2023_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}, {{< meta autores.3 >}}, {{< meta autores.4 >}}, {{< meta autores.5 >}}  
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}, {{< meta keywords.8 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo expone la percepción de las madres con relación a la sobrecarga de trabajo remunerado y no remunerado que han experimentado en la pandemia causada por el covid-19. La metodología utilizada es la investigación cualitativa con ocho madres de La Araucanía, Chile. El enfoque de la investigación es descriptivo y detalla de manera densa las experiencias personales y laborales vividas por las madres, con sus propias voces, interpretaciones y significados atribuidos. Se sustenta en el paradigma interpretativo, que prioriza la conciencia subjetiva, las creencias, los valores y las reflexiones de las mujeres participantes. El instrumento de recolección de información es la entrevista semidirigida, que consultó sobre los siguientes tópicos: 1) carga laboral que experimentan las mujeres en un día cotidiano, 2) cambios en su organización y tiempo libre durante la pandemia, 3) afectación emocional durante el confinamiento. La técnica de análisis de datos utilizada fue el análisis temático, con la finalidad de desarrollar una teoría inductiva con base en los testimonios de las mujeres que participaron en el estudio. Así, se identificaron los conceptos, ideas y sentidos resultado del análisis detallado de los datos, para precisar y conceptualizar los significados y temas que el texto contiene sobre la sobrecarga laboral que enfrentaron las mujeres en pandemia. Los principales resultados dan cuenta de una sobrecarga laboral en las madres que trajo consecuencias negativas para su salud mental. Asimismo, se constató el arraigo patriarcal en la concepción de los roles de género y el aumento del estigma impuesto a la mujer como encargada de la crianza y cuidado de los hijos y de las labores del hogar. Las principales conclusiones indican que es urgente sensibilizar respecto de las desigualdades de género, para generar procesos de transformación en las nuevas y las antiguas generaciones y para que los tiempos de crisis no sean sinónimo de estrés y sobrecarga de trabajo para las mujeres.


**BibTeX**:
```bibtex
@article{arias2023sobrecarga,
  author = {Arias, Katerin and Pinto, Bárbara and Martínez, Carol and Rodríguez, María and Benítez, Yanira},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {46},
  number = {1},
  pages = {47-67},
  doi = {}
}
```
