---
name: "Tensiones en las prácticas de co-enseñanza durante la implementación de la educación intercultural bilingüe"
title: "Tensiones en las prácticas de co-enseñanza durante la implementación de la educación intercultural bilingüe"
autores: ["Katerin Arias", "Sergio Alarcón", "Javiera Barriga", "María Solís"]
venue: "Revista Educación"
tipo: "Revista"
categories: 2022
keywords: ["2022", "Revista Educación", "Co-enseñanza", "Prácticas Pedagógicas", "Educación Intercultural", "Lengua Indígena", "Cultura Indígena"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/ART_1_ Tensiones en la Co_enseñanza EIB_ARIAS ET AL_2022_WOS_SCIELO.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd), {{< meta autores.2 >}}, {{< meta autores.3 >}}, {{< meta autores.4 >}}    
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}, {{< meta keywords.7 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: El artículo expone tensiones profesionales en las prácticas de co-enseñanza entre los actores educativos encargados de implementar el Programa de Educación Intercultural Bilingüe (PEIB) en contextos indígenas de Chile. Se da cuenta de los aportes y limitaciones de su quehacer profesional en la materialización del PEIB. El marco teórico que sustenta el estudio es el enfoque de co-enseñanza en la educación escolar, lo que implica una enseñanza colaborativa entre las personas profesionales que transmiten los saberes y conocimientos indígenas de la lengua y cultura propia en la escuela.

La metodología es cualitativa, se realizaron entrevistas semidirigidas a cuatro duplas pedagógicas encargadas de implementar el PEIB en la escuela. La técnica de análisis de la información se realiza desde un análisis de contenido de sus testimonios en el que se identifican los sentidos explícitos y latentes que transmiten a través de él. Esto se triangula con la información que emerge del proceso de codificación abierta y axial sustentado en la teoría fundamentada.

Los principales resultados dan cuenta de un desempeño profesional limitado caracterizado por una ausencia de planeación, diseño y evaluación de su propio quehacer pedagógico y didáctico para enseñar la lengua y cultura indígena en el aula. Asimismo, se carece de espacios para la planificación y coordinación entre co-enseñantes, lo que limita una adecuada implementación del PEIB.

Las principales conclusiones revelan la urgencia de focalizar los esfuerzos de mejora en cuatro aspectos: (a) claridad de roles y funciones de las personas co-enseñantes, (b) trabajo colaborativo entre co-enseñantes, (c) apoyo institucional y de la comunidad educativa para la enseñanza de la lengua y cultura indígena en el aula y (d) formación intercultural de las personas co-enseñantes para revertir los prejuicios y estigmatización hacia la niñez indígena, sus familias y, por ende, hacia el PEIB.


**BibTeX**:
```bibtex
@article{arias2022tensiones,
  author = {Arias, Katerin and Alarcón, Sergio and Barriga, Javiera and Solís, María},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {46},
  number = {2},
  pages = {19},
  doi = {https://doi.org/10.15517/revedu.v46i2.49804}
}
```
