---
name: "Transitar hacia prácticas educativas desde un enfoque educativo intercultural en La Araucanía, Chile"
title: "Transitar hacia prácticas educativas desde un enfoque educativo intercultural en La Araucanía, Chile"
autores: ["Segundo Quintriqueo Millán", "Katerin Arias-Ortega", "Vanessa Valdebenito", "Soledad Morales", "Carolina Villagra"]
venue: "Educ. Pesqui."
tipo: "Revista"
categories: 2024
keywords: ["2024", "Educ. Pesqui.", "Escolarización", "Aprendizaje en Contexto Indígena", "Educación Intercultural", "Conocimientos Indígenas"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2024_KARIAS/ART_12_EDUCACO_PESQUISA_ARIAS_ORTEGA_2024_SCOPUS.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Segundo Quintriqueo Millán.qmd), [{{< meta autores.2 >}}](../members/current/Katerin Arias-Ortega.qmd), {{< meta autores.3 >}}, {{< meta autores.4 >}}, {{< meta autores.5 >}}
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}, {{< meta keywords.6 >}}    
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: La hegemonía del conocimiento eurocéntrico occidental a través de la escolarización, ha invisibilizado históricamente otras epistemes en el medio educativo y social, omitiendo en el currículum escolar el conocimiento indígena. Por consiguiente, la educación escolar tiene el desafío de asegurar aprendizajes con pertinencia social y cultural para cada uno de los y las estudiantes.

El estudio posee como objetivo, analizar las prácticas educativas interculturales implementadas en La Araucanía-Chile desde la experiencia de 21 docentes de aula pertenecientes a 7 centros escolares. Para comprender la realidad desde los actores del medio escolar, se desarrolla la investigación educativa en coherencia con los enfoques de coconstrucción e interactivo-comunicativo-contextual a través de entrevistas semiestructuradas, complementado la sistematización y análisis de contenido, encuentros pedagógicos territoriales y experiencias de educación intercultural.

Los resultados se organizan en dos categorías emergentes: La primera, prácticas pedagógicas en perspectiva intercultural, donde se destaca a nivel discursivo, la articulación de la educación escolar con conocimientos indígenas, que consideran una planificación de las experiencias que permiten incorporar el sello intercultural, asociado a la indagación y sistematización de conocimientos locales. La segunda categoría, se refiere sensibilización sobre educación intercultural, plantea que los docentes consideran necesaria la formación en conocimientos indígenas, y la vinculación de estos en los procesos de enseñanza-aprendizaje para su fortalecimiento.

Se destaca como necesario el compromiso de la comunidad educativa, la familia y agentes de comunidad. Los desafíos que emergen se refieren a la incorporación de contenidos, métodos y finalidades educativas a la educación intercultural, respondiendo al contexto y favoreciendo la construcción de aprendizajes culturalmente pertinentes.

**BibTeX**:
```bibtex
@article{quintriqueo2024transitar,
  author = {Quintriqueo, Segundo and Arias, Katerin and Valdebenito, Vanessa and Morales, Soledad and Villagra, Carolina},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {50},
  number = {},
  pages = {15},
  doi = {https://doi.org/10.1590/S1678-4634202450270322es}
}
```
