---
name: "Voces de educadores tradicionales mapuches sobre la educación intercultural en La Araucanía, Chile"
title: "Voces de educadores tradicionales mapuches sobre la educación intercultural en La Araucanía, Chile" 
autores: ["Katerin Arias"]
venue: "Diálogo Andino"
tipo: "Revista"
categories: 2022
keywords: ["2022", "Diálogo Andino", "Educación Intercultural", "Lengua y Cultura Mapuche", "Educación Escolar"]
preprint: "pdfs/productividad/PRODUCTIVIDAD_2022_KARIAS/ART_8_Arias-Ortega_Dialogo Andino_scopus_2022.pdf"
---
**Autores**: [{{< meta autores.1 >}}](../members/current/Katerin Arias.qmd)  
**Lugar de publicación**: {{< meta venue >}}     
**Palabras Claves**: {{< meta keywords.1 >}}, {{< meta keywords.2 >}}, {{< meta keywords.3 >}}, {{< meta keywords.4 >}}, {{< meta keywords.5 >}}  
**Pre-print**: [PDF](../{{< meta preprint >}})    
**Resumen**: La incorporación del educador tradicional (sabio mapuche) al sistema educativo escolar chileno se basa en la Educación Intercultural Bilingüe para enseñar la lengua y la cultura indígena. El artículo describe los factores que influyen en la concretización de la EIB en el aula, según las voces de los educadores tradicionales mapuche. La metodología de investigación es cualitativa con enfoque descriptivo. Aplicamos entrevistas semidirigidas a los participantes y analizamos la información recopilada utilizando teoría fundamentada. Los resultados muestran que el educador tradicional percibe prácticas de discriminación e invisibilidad durante la concretización de la EIB. Este escenario incrementa el racismo y la discriminación hacia los indígenas en la educación escolar. Concluimos que los actores del sistema educativo y del entorno social se resisten a incluir a los educadores tradicionales, y no aceptan la implementación de la EIB. Creemos que estos problemas podrían revertirse articulando principios pedagógicos y educativos indígenas dentro del sistema escolar. De esta forma, es posible fortalecer la identidad sociocultural del estudiante y aumentar el compromiso de la ciudadanía con una sociedad intercultural.


**BibTeX**:
```bibtex
@article{arias2022voces,
  author = {Arias, Katerin},
  title = {{< meta title >}},
  journal = {{< meta venue >}},
  year = {{< meta categories.1 >}},
  volume = {67},
  number = {},
  pages = {31-41},
  doi = {}
}
```
